import type {Metadata, Viewport} from "next";
import "./globals.css";
import {Footer2} from "@/app/components/Footer";
import { Inter } from "next/font/google"
import {Contact7} from "@/app/components/Contact";
import Header from "@/app/components/Header";
import CookieBanner from "@/app/components/CookieBanner";

const inter = Inter({
    subsets: ["latin", "latin-ext" ],
    display: "swap",
    variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cz" className="scroll-smooth">
      <body
          className={`${inter.variable} ${inter.variable} antialiased flex flex-col justify-center px-4 md:px-8 py-6 md:py-8 gap-8 min-h-screen bg-background text-foreground`}      >
      <Header></Header>
      <main className="flex flex-col gap-20 md:gap-28 max-w-7xl mx-auto w-full">
          {children}
          <Contact7></Contact7>
          <CookieBanner></CookieBanner>
      </main>
      <footer className="max-w-7xl mx-auto w-full">
          <Footer2></Footer2>
      </footer>
      </body>
    </html>
  );
}
